---
title: "Lentivirus production and transduction"
format: html
editor: visual
author: Carrie Tse
date: "`r Sys.Date()`"
---
# Lentivirus production

## Materials

- Plasmids
  - lentiviral packaging plasmid [psPAX2](https://www.addgene.org/12260/) (encoding HIV-1 Gag, Pol, Tat and Rev proteins)
  - lentiviral envelope plasmid [pMD2.G](https://www.addgene.org/12259/) (encoding the VSV G envelope protein)
  - lentiviral expression plasmids (MORF)
- 293T/293FT cells 
- DMEM, high glucose, GlutaMAX Supplement, pyruvate (cat. 10569010)
- Opti-MEM™ I Reduced Serum Medium (OptiMEM) (cat.)
- FBS
- PBS
- 0.05% trypsin/EDTA
- tissue culture flasks/dishes
- PEG solution (BioCat, K904-50-BV)
- Lipofectamine 3000 Transfection Reagent (cat. L3000015)
- 15- and 50-ml conical centrifuge tubes, sterile
- 0.45-mM PVDF/PES filter
- 0.22 μm pore size filters units

### Equipments

-   Ultraentrifuge (50,000 × g)
-   TC incubator (humidified, 37°C, 5% CO~2~)

## NOTE

-   All solutions and equipment coming into contact with living cells must be sterile, and proper aseptic technique should be used accordingly.
-   All medium should be pre-warmed to 37°C.
-   All culture incubations should be performed in a humidified, 37°C, 5% CO~2~ incubator unless otherwise specified.
-   Do not add pen-strep to the medium.
-   All liquid waste should be treated with 10% bleach prior to disposal.

# Transfection

**For T25 flask ([Scale the values depending on the cell culture vessel used](#scale))**

### Preparation

1. Complete culturing medium: DMEM, GlutaMAX Supplement, pyruvate, 10% FBS
2. Lentivirus packaging medium: 
    - 474 mL OptiMEM I Reduced Serum Medium, GlutaMAX Supplement
    - 25 mL FBS
    - 1 mL sodium pyruvate (100 mM)

### Day 1 (afternoon): cell seeding 
1. Seed 293T cells onto 6-well plate at 70-80% confluency. ~1.2 x 10^6^ cells per well in 2 mL of lentivirus packaging medium.
2. Incubate cells overnight at 37°C, 5% CO~2~.

### Day 2 (morning): transfection
1. Prepare Tube A: 625 uL OptiMEM I Reduced Serum Medium, 15 uL P3000 Enhancer Reagent, 1.7 ug pMD2.G, 2.6 ug psPAX2, 7.7 ug expression plasmid.
2. Prepare Tube B: 625 uL OptiMEM I Reduced Serum Medium, 17.5 uL Lipofectamine 3000^[Lipofectamine 3000 should be used within 15 min of dilution.].
3. Mix Tube A and B. Incubate for 10-20 min at room temperature.
4. Prior to adding mixture, 1 mL of medium from each well, leaving a total of 1 mL in each well.
5. Add 500 uL of lipid-DNA complex to each well, avoid disrupting cells. Gently agitate plate to evenly distribute.   
6. Incubate plate for 6 hours at 37°C, 5% CO~2~.
7. At 6 hours post-transfection, change plate medium with 2 mL of lentivirus packaging medium.
8. Return plate to incubator, incubate overnight at 37°C, 5% CO~2~.

> Recommended start time: 10 am, medium replacing time: 4 pm.

### Day 4 (morning): harvest of virus

1. At 48 h post-transfection, collect 2 mL cell supernatant from each well.
2. Filter with a 0.45 um PVDF filter, aliquote and store at -80°C.



# Transduction




# References
[2006-Salmon-Trono](https://doi.org/10.1002/0471142301.ns0421s37)\
[2023-Joung-Zhang](https://doi.org/10.1016/j.cell.2022.11.026)\
[Improve lentiviral production using
Lipofectamine 3000 reagent](https://content.protocols.io/files/eg26biprp.pdf)\

# Scale

| Cell_culture_vessel                       | T225  | T175  | T75   | T25  | 10-cm | 6-cm | 6-well |
|----------------------------------|-------|-------|-------|------|-------|------|--------|
| Surface area (cm²)               | 225   | 175   | 75    | 25   | 55.68 | 21.12 | 9.6    |
| **Seeding**                       |       |       |       |      |       |      |        |
| Lentivirus packaging medium (mL)              | 48    | 37    | 16    | 5.3  | 12    | 4    | 2      |
| Cells (cells)                    | 2.85E+07 | 2.21E+07 | 9.50E+06 | 3.17E+06 | 7.00E+06 | 2.60E+06 | 1.20E+06 |
| Seeding density (cells/mL)       | 5.99E+05 | 5.97E+05 | 5.94E+05 | 5.97E+05 | 5.83E+05 | 6.50E+05 | 6.00E+05 |
| **Tube A**                       |       |       |       |      |       |      |        |
| P3000 Enhancer (µL)              | 135   | 105   | 45    | 15   | 35    | 13   | 6      |
| OptiMEM only (µL)                | 5625  | 4600  | 2000  | 625  | 1500  | 500  | 250    |
| pMD2.G (µg)                      | 15.3     | 11.9     | 5.1      | 1.7      | 3.8     | 1.4    | 0.7    |
| psPAX (µg)                       | 23.4     | 18.2     | 7.8      | 2.6      | 5.8     | 2.2    | 1.0    |
| Target plasmid (MORF) (µg)       | 30.6     | 23.8     | 10.2     | 3.4      | 7.6     | 2.9    | 1.3    |
| **Tube B**                       |       |       |       |      |       |      |        |
| OptiMEM only (µL)                | 5625  | 4600  | 2000  | 625  | 1500  | 500  | 250    |
| Lipofectamine 3000 (µL)          | 165   | 129   | 55    | 17.5 | 41    | 15   | 7      |

[Back to Transfection](#transfection)

# Titration

The titer range should between 1 × 10^6^ and 6 × 10^7^ IFU mL^−1^.

## Functional titration: Limiting Dilution (Colony Counting)

## Materials

-   6-well cell culture treated plates
-   15 mL conical vials
-   Cell line of choice

## Reagents

- Hexadimethrine bromide (2 mg/mL stock) Product No. H9268
- Puromycin (10 mg/mL stock) Product No. P9620
- Crystal Violet Solution, Product No. HT90132
- PBS
- Paraformaldehyde

## Equipments

-   microscope

## Preparation

**DMEM Complete**

Add 10% v/v FBS into DMEM.

**Puromycin (10 mg/mL stock)**

**Hexadimethrine bromide (2 mg/mL stock)**

**4% paraformaldehyde**

## Procedure

### Transduciton

1.  Seed 1.5-2 × 10^5^ cells to each well of a 6-well plate in DMEM Complete meidum without any antibiotics.[^1]

2.  Incubate the cells overnight at 37°C, 5% CO~2~.

3.  Thaw lentivirus on ice.[^2]

4.  Prepare 15 mL of media containing hexadimethrine bromide (final concentration 8 μg/mL).[^3]

[^1]: The growth rate of cells vary. Adjust the seeding number to accommodate a confluency of 30-50% upon transduction.

[^2]: Prolonged exposure to ambient temperatures will decrease the titer; Multiple freeze-thaw cycles should be avoided.

[^3]: Hexadimethrine bromide enhances transduction of most cell types. BUT, some cells (e.g. primary neurons) are sensitive to hexadimethrine bromide and this step should be skipped. If working with a cell type for the first time, have a hexadimethrine control only to determine cell sensitivity.

**with hexadimethrine bromide**

5. Prepare 2 mL 10-fold serial dilutions over a range of 1 x 10^-2^ to 1 x 10^-6^. Mix gently by inverting the tubes five to ten times.

6. For each well of the 6-well plate, add 1 mL of medium containing hexadimethrine bromide, then add 1 mL of each of the lentiviral dilutions.

7.  Incubate cells at 37°C, 5% CO~2~ for 18-20 h.

8. (Day 3) Remove the media containing lentiviral particles from wells. Add 2 mL fresh DMEM complete (without hexadimethrine bromide) to each well.^[Add the medium slowly to avoid disturbing the cells]

9. Incubate cells at 37°C, 5% CO~2~ for 18-20 h.

10. (Day 4) Remove media from wells. Add fresh media containing puromycin.^[Typically 2 -10 μg/mL are sufficient to kill most untransduced mammalian cell types.]
**Puromycin titration (kill curve) should be performed when working with a new cell type.**

11. (Days 5 – 14). Replace media containing puromycin every 3 days. Observe the cells every day to monitor the death of cells that are sensitive to puromycin.

**without hexadimethrine bromide**

4.  Remove culture medium from each well and add 975 μl fresh medium without FBS and antibiotics.

5.  Perform 5-fold serial dilution of lentivirus.

6.  Gently add 25 μl of the diluted lentivirus in each well of 6-well plate.

7.  Gently mix the plate

    \[Optional: Centrifuge at 2000 RPM for 2 hours at room temperature\]

8.  Incubate cells at 37°C, 5% CO~2~ for 6 h.

9.  Add 2 ml DMEM Complete with antibiotics. Incubate cells at 37°C, 5% CO~2~ for 42 h.

10. Change medium with fresh DMEM containing 2 μg/ml puromycin, 10% FBS and antibiotics.

11. Continue to incubate at 37°C, 5% CO~2~ for 4~6 days, and replace culture medium every other day with puromycin-containing medium.

12. Observe the cells every day to monitor the death of cells that are sensitive to puromycin.

### Counting

1. Remove the culture medium from each well.

2. Gently rinse the cells with 1 ml PBS.

3. Fix cells with 1 ml of 4% paraformaldehyde for 15 min at room temperature.

4. Wash one time with 1 ml of PBS.

5. Stain cells with 1 ml of crystal violet solution at room temperature for 20 min.

6.Remove crystal violet solution.

7. Wash cells with PBS x 3 times (3 ml each time).

8. Count the blue-stained colonies using a microscope at a magnification of 40×.

9. Calculate the lentiviral titer (TU/ml) by multiplying the number of colonies per well by the dilution factor.


# Puromycin titration (kill curve)
1. Plate 1.6 x 10^4^ cells in to wells of a 96-well plate with 120 μl fresh media.

2. The next day, change to medium containing 500–10,000 ng/mL of puromycin for selected wells.

3. Examine viability every 2 days.

4. Culture for 10 – 14 days. Replace the media containing puromycin every 3 days.

5. The minimum concentration of puromycin that causes complete cell death after 3 -5 days should be used for that cell type.


# Timing

Day 0: Seed 293T packaging cells.

Day 1 (pm): Transfect packaging cells.

Day 2 (am): 18 h post-transfection. Remove media, replace with fresh media.

Day 3-4 (am): Harvest virus.

Day 5-20: Titration.



# References

2002-Ramezani-Hawley\
[Overview of the HIV-1 Lentiviral Vector System](https://doi.org/10.1002/0471142727.mb1621s60)

2006-Cronin-Reiser  [Altering the Tropism of Lentiviral Vectors through Pseudotyping](https://doi.org/10.2174/1566523054546224)

2021-Ng-Church  [A comprehensive library of human transcription factors for cell fate engineering](https://doi.org/10.1038/s41587-020-0742-6)

2007-Salmon-Trono\
[Production and titration of lentiviral vectors](https://doi.org/10.1002/0471142905.hg1210s54)

**Other reference protocol**

[Addgene protocol](https://www.addgene.org/protocols/lentivirus-production/)

[Thermo protocol](https://www.thermofisher.com/hk/en/home/life-science/cell-culture/cell-culture-learning-center/cell-culture-resource-library/cell-culture-transfection-application-notes/improve-lentiviral-production-using-lipofectamine-3000-reagent.html)

[Sigma protocol](https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/marketing/global/documents/383/004/lentiviraltiterprotocol.pdf?srsltid=AfmBOoo0bLOD67rEEWfbodChfK4UiHZMhQQ_zUp74ZtGTAiyAajQp7_u)

------------------------------------------------------------------------
