---
title: "RNA extraction using TRIzol LS Reagent"
format: html
editor: visual
author: Carrie Tse
date: "`r Sys.Date()`"
---
# Description

Invitrogen™ TRIzol™ LS Reagent
RNA and DNA extraction from liquid samples (i.e., blood)


• Isolated RNA can be used in RT-PCR, Northern Blot analysis,
Dot Blot hybridization, poly(A)+ selection, in vitro translation, RNase protection assay, and molecular cloning.

• Isolated DNA can be used in PCR, Restriction Enzyme
digestion, and Southern Blots.

• Isolated protein (if needed) can be used for Western Blots, recovery of some enzymatic activity, and some immunoprecipitation.


# Equipment
- Water bath or heat block at 55–60°C
- Centrifuge (capable of reaching 12,000 *g* and 4°C)

# Reagents
**For RNA extraction**
- Isopropanol 
- Chloroform
- Ethanol, 75%
- RNase-free water or 0.5% SDS

**For DNA extraction**
- 0.1 M sodium citrate in 10% ethanol, pH8.5
- 8 mM NaOH
- HEPES
- 1 mM EDTA

# Note
- Biological fluids with high levels of contamination material (e.g. whole blood) should be diluted 1:1 with RNase-free water.

- Perform all steps at room temperature (20–25°C) unless
otherwise noted.

- Use cold TRIzol™ LS Reagent if the starting material contains
high levels of RNase.

\newpage

# Procedure

## Lyse samples and separate phases

1. Add 0.75 mL TRIzol LS Reagent per 0.25 mL of sample volume. (e.g. add 6 mL TRIzol LS Reagent to 2 mL diluted whole blood.)

2. Homogenize the sample by pipetting up and down.[^Samples can be stored at 4°C overnight or -20°C for up to a year.]

> for samples with high fat content, centrifuge the lysate for 5 min at 12,000 *g* at 4°C, transfer the clear supernatant to a new tube.

3. Add 0.2 mL chloroform per 0.75 mL of TRIzol LS Reagent. (e.g. add 1.6 mL chloroform per 6 mL TRIzol LS Reagent)

4. Securely cap the tube, incubate for 2-3 min.

5. Centrifuge for 15 min at 12,000 *g* at 4°C.

6. Transfer the aqueous phase containing the RNA to a new tube. **Avoid transfer any interphase or organic layer into the pipette** 



## RNA isolation
### RNA precipitation

1. Add 0.5 mL isopropanol to the aqueous phase per 0.75 mL TRIzol LS Reagent used. (e.g. add 4 mL isopropanool per 6 mL TRIzol LS Reagent used)

2. Incubate for 10 min.

3. Centrifuge for 10 min at 12,000 *g* at 4°C.[^Total RNA precipitate forms a white gel-like pellet at the bottom of the tube.]

4. Transfer supernatant to another tube, keep until precipitation succeed. # CHECK what to do if no RNA pellet

### Washing 

5. Resuspend the pellet in 1 mL of 75% ethanol per 0.75 mL of TRIzol LS Reagent used for lysis (e.g. 8 mL 75% ethanol per 6 mL TRIzol LS Reagent used)[^RNA can be stored in 75% ethanol for at least 1 yr at -20°C, or at least 1 week at 4°C.]

6. Vortex the sample briefly, centrifuge for 5 min at 7500 *g* at 4°C.

7. Discard the supernatant with a micropipettor.

8. Vacuum or air dry the RNA pellet for 5-10 min.[^do NOT overdry the pellet or dry by vacuum centrifuge. Partially dissolved RNA havev an A230/280 ratio <1.6.]

### Solubiize the RNA

9. Resuspend the pellet in 20-50 uL RNase-free water, 0.1 mM EDTA, or 0.5% SDS solution.

10. Incubate in a water bath or heat block at 55-60°C for 15 min.

11. Proceed to downstream experiment or store at -80°C.


## DNA isolation
### DNA precipitation

1. Remove any remaining aqueous phase overlying the interphase.

2. Add 0.3 mL of 100% ethanol per 0.75 mL TRIzol LS Reagent used for lysis. (e.g. 2.4 mL 100 % ethanol per 6 mL TRIzol LS Reagent used)

3. Cap the tube, mix by inverting the tube several times.

4. Incubate 2-3 min.

5. Centrifuge for 5 min at 2000 *g* at 4°C.

6. For protein isolation: Transfer the phenol-ethanol supernatant to a new tube.

### Wash

7. Resuspend the pelelt in 1 mL of 0.1 M sodium citrate in 10% ethanol, pH8.5, per 0.75 mL TRIzol LS Reagent used for lysis. (e.g. 8 mL 0.1 M sodium citrate in 10% ethanol, pH8.5, per 6 mL TRIzol LS Reagent used.) 

8. Incubate for 30 min. Mix occasionally by gentle inversion.[^DNA can be stored in sodium citrate/ethanol for at least 2 h.]

9.Centrifuge for 5 min at 2000 *g* at 4°C.

10. Discard supernatant with a micropipettor.

11. Repeat step 7-10 once. 
> For large DNA pellets (>200 ug), repeat twice.

12. Resuspend the pellet in 1.5-2 mL 75% ethanol per 0.75 mL of TRIzol LS Reagent used for lysis (e.g. 12-16 mL 75% ethanol per 6 mL TRIzol LS Reagent used.)

13. Incubate for 10-20 min. Mix occasioinally by gentle inversion.[^DNA can be stored in 75% ethanol for several months at 4°C.]

14. Centrifuge for 5 min at 2000 *g* at 4°C.

15. Discard supernatant with a micropipettor.

16. Vacuum or air dry the DNA pellet for 5-10 min.[^do NOT dry by vacuum centrifuge.]

### Solubilize the DNA

17. Resuspend the pellet in 0.3-0.6 mL of 8 mM NaOH by pipetting up and down.[^resuspending the DNA in mild base as isolated DNA does not resuspend well in water or Tris buffer.]

18. Centrifuge for 10 min at 12,000 *g* at 4°C to remove insoluble materials.

19. Transfer the supernatant to a new tube. Adjust pH as needed with HEPES. 

20. Proceed to downsteam applications or store at 4°C overnight. For longer-term storage at -20°C, adjust the pH to 7-8 with HEPES and add 1 mM EDTA. 



## Protein isolation
### Protein precipitation

1. Remove any remaining aqueous phase overlying the interphase.

2. Add 0.3 mL of 100% ethanol per 0.75 mL of TRIzol LS Reagent used for lysis. 

3. Cap the tube, mix by inverting the tube several times.

4. Incubate for 2–3 min.

5. Centrifuge for 5 min at 2000 × g at 4°C to pellet the DNA.

6. Transfer the phenol-ethanol supernatant to a new tube.

7. Add 1.5 mL of isopropanol to the phenol-ethanol supernatant per 0.75 mL of TRIzol LS Reagent used for lysis.

8. Incubate for 10 min.

9. Centrifuge for 10 min at 12,000 *g* at 4°C to pellet the proteins.

10. Discard the supernatant with a micropipettor.

### Wash

11. Prepare a wash solution consisting of 0.3 M guanidine hydrochloride in 95% ethanol.

12. Resuspend the pellet in 2 mL of wash solution per 0.75 mL of TRIzol LS Reagent used for lysis.

13. Incubate for 20 min.[^The proteins can be stored in wash solution for at least 1 month at 4°C or for at least 1 yr at –20°C.]

14. Centrifuge for 5 min at 7500 *g* at 4°C.

15. Discard the supernatant with a micropipettor.

16. Repeat step 12–15 twice.

17. Add 2 mL of 100% ethanol, then mix by vortexing briefly.

18. Incubate for 20 min.

19. Centrifuge for 5 min at 7500 *g* at 4°C.

20. Discard the supernatant with a micropipettor.

21. Air dry the protein pellet for 5–10 min.[^do NOT dry by vacuum centrifuge.]

### Solubilize the protein

22. Resuspend the pellet in 200 uL of 1% SDS by pipetting up and down.
[^To ensure complete resuspension of the pellet, incubate the sample at 50°C in a water bath or heat block.]

23. Centrifuge for 10 min at 10,000 *g* at 4°C to remove insoluble materials.

24. Transfer the supernatant to a new tube.

25. Measure protein concentration by Bradford assay (SDS concentration mush be <0.1%), then proceed directly to downstream applications, or store the sample at –20°C.
